### PR TITLE
Update to current version

### PR DESCRIPTION
**Pull request by wasbazi**
The version in the repository seems to be throwing off the dependencies of my project. When I have codacy-coverage in my setup.py file and install my dependencies it finds the latest version fine. But when I freeze my requirements it puts the version in the file as

`codacy-coverage==1.1.1`

This makes it hard to install from the requirements.txt file since there is no version 1.1.1 of codacy-coverage.

### CODE REVIEW

**Comment by machadoit** [comment]
Thanks for your PR, but as soon as we publish it, the version will then change to 1.1.13.

I am going to reject your PR, but going to add the correct version as a part of our publish process.

**Comment by wasbazi** [comment]
Thanks for adding this in, do you mean 1.2.13?

**Comment by machadoit** [comment]
Yeah I meant 1.2.x. Anyhow, the latest version is now 1.2.16, and now our version.py will always have the correct version =)

**Comment by machadoit** [comment]
I also had updated the default version, the version with everything up to date is now 1.2.18

**Pull request closed without merging**
