### PR TITLE
Option to use token as argument

### PR DESCRIPTION
**Pull request by IceflowRE**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
LGTM 👍 

@mrfyda

**Review by rtfpessoa — APPROVED** [review]

**Comment by rtfpessoa** [comment]
@IceflowRE I just enabled builds from forks in CircleCI. Can you amend the commit so that CircleCI starts the build?

**Comment by IceflowRE** [comment]
Done.

**Comment by rtfpessoa** [comment]
Released as version 1.3.9

**Pull request merged**
